add function db_remote_product()
peeredu/command_project_001 pull request #72
Opened 2024-04-02 20:00 UTC by SavushkinSV

2024-04-02 20:25 UTC, fortune76 requested changes

2024-04-02 20:25 UTC, fortune76 commented on data/src/db_api.c
> +int db_remote_product(MYSQL *conn, const int id) {
remove

2024-04-02 20:25 UTC, fortune76 commented on data/src/db_api.c
> +    if (NULL == stmt) error = 1;
т.к. операции с бд достаточно трудозатратное мероприятие, и в целом это обработка ошибок, а не результата, предлагаю отойти от школьных предрассудков насчет ретерна, и использовать его сразу, а не ждать пока ошибочный запрос пройдет все итерации

2024-04-02 20:25 UTC, fortune76 commented on data/src/db_api.c
> +    if (NULL == stmt) error = 1;
тут тоже предлагаю ретерн делать сразу при ошибке

2024-04-02 20:25 UTC, fortune76 commented on data/src/db_api.c
> +        bool prepare_fail = mysql_stmt_prepare(stmt, command, strlen(command));
это можно назвать error_code, и убрать переменную error вообще, возвращать error_code

2024-04-03 09:41 UTC, antsht commented
Я двумя руками за принцип Fail fast, если ошибка не допускает возможности продолжать работу - падать лучше сразу.
https://uchet-jkh.ru/i/proizoslo-isklyucenie-fail-fast/

2024-04-03 17:04 UTC, fortune76 submitted a review, later dismissed

2024-04-03 17:05 UTC, antsht submitted a review, later dismissed

2024-04-03 17:08 UTC, fortune76 approved these changes

2024-04-03 17:08 UTC, antsht approved these changes

2024-04-03 17:08 UTC, merged